name: Deploy webiste

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check AWS CLI
        run: |
          aws --version
      - name: Run a multi-line script
        run: |
          aws s3api list-buckets
